kaisellgren/mailer

- CHANGELOG.md
- lib/src/envelope.dart
- lib/src/smtp/smtp_client.dart
- pubspec.yaml
A little sprinkling of dartfmt
> Fix new line endings to be `\r\n`

- pubspec.yaml
fixes https://github.com/kaisellgren/mailer/issues/50
> fix: relax logging and charcode versions

- CHANGELOG.md
- README.md
- lib/smtp_server.dart
- lib/smtp_server/hotmail.dart
- lib/smtp_server/mailgun.dart
- pubspec.yaml
> export smtp_servers in smtp_server.dart

- CHANGELOG.md
- example/send_gmail.dart
- lib/src/smtp/internal_representation/internal_representation.dart
- lib/src/smtp/internal_representation/ir_header.dart
- lib/src/smtp/validator.dart
- lib/src/utils.dart
- pubspec.yaml
> fix: impr RegExp which validates name of an email-address

- CHANGELOG.md
- lib/mailer.dart
- pubspec.yaml
> add `catchExceptions` flag to `send` command

- CHANGELOG.md
- lib/src/entities/attachment.dart
- lib/src/smtp/smtp_client.dart
- pubspec.yaml
fix: assign catchExceptions flag if null
fixes #96
> version 2.5.1

- CHANGELOG.md
- lib/src/entities/attachment.dart
- lib/src/smtp/smtp_client.dart
- pubspec.yaml
branch v2 will become the maintenance branch of mailer versions below 3
> merge 2.5.1 into v2 branch

- lib/src/smtp/connection.dart
- lib/src/smtp/internal_representation/ir_content.dart
- pubspec.yaml
https://groups.google.com/forum/#!topic/flutter-announce/LTe4SYU8-0Q
> fix: file operations return an Uint8List instead of List<Int>

- CHANGELOG.md
- lib/src/smtp/internal_representation/conversion.dart
- pubspec.yaml
- test/send_test.dart
- test/split_test.dart
> fix: text splitting for base64 conversion

- lib/smtp_server/hotmail.dart
I have updated the smtp server address for hotmail, since the old smtp server address is not working. 
I have tested the code myself, its working fine.
> Updated hotmail SMTP server address

- CHANGELOG.md
- lib/smtp_server/gmail.dart
- pubspec.yaml
It's hard to really test this, and I'm sure there are other ways to authenticate..
I just tried to outline some hints.
In any case, having tried `gmailXoauth2` it seems rather useless as it doesn't follow the encoding patterns layed out in:
https://developers.google.com/gmail/imap/xoauth2-protocol#the_sasl_xoauth2_mechanism
> Improved gmail integration utilities

- example/gmail_xoauth2/obtain_credentials.dart
- example/gmail_xoauth2/send_mail.dart
- example/send_gmail.dart
- lib/smtp_server.dart
- lib/src/entities/address.dart
- lib/src/entities/attachment.dart
- lib/src/entities/message.dart
- lib/src/entities/send_report.dart
- lib/src/smtp/capabilities.dart
- lib/src/smtp/connection.dart
- lib/src/smtp/internal_representation/conversion.dart
- lib/src/smtp/internal_representation/internal_representation.dart
- lib/src/smtp/internal_representation/ir_content.dart
- lib/src/smtp/internal_representation/ir_header.dart
- lib/src/smtp/internal_representation/ir_message.dart
- lib/src/smtp/mail_sender.dart
- lib/src/smtp/smtp_client.dart
- lib/src/smtp/validator.dart
- lib/src/utils.dart
- pubspec.yaml
- test/send_test.dart
I've migrated the project to null safety as I have a dependant project.
If you could review and publish to pub.dev that would appreciated.
> Migrated to null safetey.

- CHANGELOG.md
- lib/src/smtp/smtp_client.dart
- pubspec.yaml
- Fixes #175.
- Also at https://github.com/dart-lang/pub-dev/issues/4934.
> Fix null-safety bug with bad cast.

- lib/src/smtp/smtp_client.dart
Makes it easier to debug what went wrong. Maybe, you're hitting a quota limit or authentication fails because the mechanism isn't supported by the server -- or your temporary credentials have expired.
> Include the SMTP error code in the authentication failure exception

- lib/src/entities/address.dart
- test/address_test.dart
- test/parse_mailboxes_test.dart
Also fixes quoting names when necessary before sending email.
> Add support for parsing a list of rfc5322 mailbox-formatted addresses

- README.md
> doc: add note for 2fa with app password / oauth in README

- CHANGELOG.md
- analysis_options.yaml
- example/send_gmail.dart
- lib/smtp_server/gmail.dart
- lib/src/smtp/capabilities.dart
- lib/src/smtp/connection.dart
- lib/src/smtp/internal_representation/ir_header.dart
- lib/src/smtp/mail_sender.dart
- lib/src/smtp/smtp_client.dart
- lib/src/smtp/validator.dart
- pubspec.yaml
- test/message_out_test.dart
- test/messages/message_all.dart
- test/messages/message_helpers.dart
- test/messages/message_utf8_long_subject_long_body.dart
- test/split_test.dart
fix all linter warnings.
gmail is no longer deprecated as using 2-factor authentication with an app password works fine.
> feat: allow intl 0.18; switch to lints

- lib/src/smtp/smtp_client.dart
Hello @kaisellgren,
I've implemented SMTP AUTH PLAIN method, so - please merge :)
> implemented AUTH PLAIN

- CHANGELOG.md
- lib/src/smtp/mail_sender.dart
- pubspec.yaml
> fix: close connections in finally block

- CHANGELOG.md
- pubspec.yaml
> feat: allow mime 2.0.0
